arch: ppc64le
dist: focal
  
jobs:
  include:
    - name: Clone and checkout
      stage: clone and checkout
      workspaces:
        create:
          name: git_repo
          paths: 
            - "${TRAVIS_BUILD_DIR}/stackrox/collector"
      script:
        - |
          git clone --recurse-submodules https://github.com/stackrox/collector && cd collector
          git checkout d9865f88b0163cfc8e91ffb6b236762547433d24
  
    - name: Build image
      stage: build
      workspaces:
        use:
          name: git_repo
      stage: build
      before_script:
        - sudo apt-get update -y; sudo apt-get install make gcc snapd docker.io -y;
        - sudo snap install go --classic --channel=1.19/stable
      script:
        - ls -lha
        - pwd
        - BUILD_BUILDER_IMAGE=true make image
