arch: ppc64le
dist: focal

before_script:
  - sudo apt-get update -y; sudo apt-get install make gcc snapd docker.io -y;
  - sudo snap install go --classic --channel=1.19/stable
  - docker version
  - go version
  
jobs:
  include:
    - name: Clone and checkout
      script:
        - |
          git clone --recurse-submodules https://github.com/stackrox/collector && cd collector
          git checkout d9865f88b0163cfc8e91ffb6b236762547433d24
  
    - name: Build image
      script: BUILD_BUILDER_IMAGE=true make image
